var cards = [
    {picture: "$J", symbol: "$", point: -2, flipped: false},
    {picture: "$J", symbol: "$", point: -2, flipped: false},

    {picture: "KC", symbol: "K", point: 0, flipped: false},
    {picture: "AC", symbol: "A", point: 1, flipped: false},
    {picture: "2C", symbol: "2", point: 2, flipped: false},
    {picture: "3C", symbol: "3", point: 3, flipped: false},
    {picture: "4C", symbol: "4", point: 4, flipped: false},
    {picture: "5C", symbol: "5", point: 5, flipped: false},
    {picture: "6C", symbol: "6", point: 6, flipped: false},
    {picture: "7C", symbol: "7", point: 7, flipped: false},
    {picture: "8C", symbol: "8", point: 8, flipped: false},
    {picture: "9C", symbol: "9", point: 9, flipped: false},
    {picture: "10C", symbol: "10", point: 10, flipped: false},
    {picture: "JC", symbol: "J", point: 10, flipped: false},
    {picture: "QC", symbol: "Q", point: 10, flipped: false},

    {picture: "KD", symbol: "K", point: 0, flipped: false},
    {picture: "AD", symbol: "A", point: 1, flipped: false},
    {picture: "2D", symbol: "2", point: 2, flipped: false},
    {picture: "3D", symbol: "3", point: 3, flipped: false},
    {picture: "4D", symbol: "4", point: 4, flipped: false},
    {picture: "5D", symbol: "5", point: 5, flipped: false},
    {picture: "6D", symbol: "6", point: 6, flipped: false},
    {picture: "7D", symbol: "7", point: 7, flipped: false},
    {picture: "8D", symbol: "8", point: 8, flipped: false},
    {picture: "9D", symbol: "9", point: 9, flipped: false},
    {picture: "10D", symbol: "10", point: 10, flipped: false},
    {picture: "JD", symbol: "J", point: 10, flipped: false},
    {picture: "QD", symbol: "Q", point: 10, flipped: false},

    {picture: "KH", symbol: "K", point: 0, flipped: false},
    {picture: "AH", symbol: "A", point: 1, flipped: false},
    {picture: "2H", symbol: "2", point: 2, flipped: false},
    {picture: "3H", symbol: "3", point: 3, flipped: false},
    {picture: "4H", symbol: "4", point: 4, flipped: false},
    {picture: "5H", symbol: "5", point: 5, flipped: false},
    {picture: "6H", symbol: "6", point: 6, flipped: false},
    {picture: "7H", symbol: "7", point: 7, flipped: false},
    {picture: "8H", symbol: "8", point: 8, flipped: false},
    {picture: "9H", symbol: "9", point: 9, flipped: false},
    {picture: "10H", symbol: "10", point: 10, flipped: false},
    {picture: "JH", symbol: "J", point: 10, flipped: false},
    {picture: "QH", symbol: "Q", point: 10, flipped: false},

    {picture: "KS", symbol: "K", point: 0, flipped: false},
    {picture: "AS", symbol: "A", point: 1, flipped: false},
    {picture: "2S", symbol: "2", point: 2, flipped: false},
    {picture: "3S", symbol: "3", point: 3, flipped: false},
    {picture: "4S", symbol: "4", point: 4, flipped: false},
    {picture: "5S", symbol: "5", point: 5, flipped: false},
    {picture: "6S", symbol: "6", point: 6, flipped: false},
    {picture: "7S", symbol: "7", point: 7, flipped: false},
    {picture: "8S", symbol: "8", point: 8, flipped: false},
    {picture: "9S", symbol: "9", point: 9, flipped: false},
    {picture: "10S", symbol: "10", point: 10, flipped: false},
    {picture: "JS", symbol: "J", point: 10, flipped: false},
    {picture: "QS", symbol: "Q", point: 10, flipped: false},
];

module.exports = cards;